# Generated by Django 5.2.4 on 2025-07-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='comentario',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='puntaje',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
